// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SellerBox.Common;

namespace SellerBox.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20181109131501_Add_ShortUrlsPassedClicks")]
    partial class Add_ShortUrlsPassedClicks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SellerBox.Models.Database.BirthdayScenarios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DaysBefore");

                    b.Property<long>("IdGroup");

                    b.Property<Guid>("IdMessage");

                    b.Property<bool>("IsEnabled");

                    b.Property<bool>("IsMale");

                    b.Property<byte>("SendAt");

                    b.HasKey("Id");

                    b.HasIndex("IdGroup");

                    b.HasIndex("IdMessage");

                    b.ToTable("BirthdayScenarios");
                });

            modelBuilder.Entity("SellerBox.Models.Database.BirthdayWallScenarios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("IdGroup");

                    b.Property<Guid>("IdMessage");

                    b.Property<long>("IdVkUser");

                    b.Property<bool>("IsEnabled");

                    b.Property<byte>("SendAt");

                    b.HasKey("Id");

                    b.HasIndex("IdGroup");

                    b.HasIndex("IdMessage");

                    b.HasIndex("IdVkUser");

                    b.ToTable("BirthdayWallScenarios");
                });

            modelBuilder.Entity("SellerBox.Models.Database.ChainContents", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IdChain");

                    b.Property<Guid?>("IdExcludeFromChain");

                    b.Property<Guid?>("IdGoToChain");

                    b.Property<Guid?>("IdMessage");

                    b.Property<int>("Index");

                    b.Property<bool>("IsOnlyDayTime");

                    b.Property<int>("SendAfterSeconds");

                    b.HasKey("Id");

                    b.HasIndex("IdChain");

                    b.HasIndex("IdExcludeFromChain");

                    b.HasIndex("IdGoToChain");

                    b.HasIndex("IdMessage");

                    b.ToTable("ChainContents");
                });

            modelBuilder.Entity("SellerBox.Models.Database.Chains", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("IdGroup");

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("IdGroup");

                    b.ToTable("Chains");
                });

            modelBuilder.Entity("SellerBox.Models.Database.ChatScenarioContents", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IdChatScenario");

                    b.Property<Guid>("IdMessage");

                    b.Property<long>("Step");

                    b.HasKey("Id");

                    b.HasIndex("IdChatScenario");

                    b.ToTable("ChatScenarioContents");
                });

            modelBuilder.Entity("SellerBox.Models.Database.ChatScenarios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Formula");

                    b.Property<bool>("HasFormula");

                    b.Property<long>("IdGroup");

                    b.Property<string>("InputMessage");

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("IdGroup");

                    b.ToTable("ChatScenarios");
                });

            modelBuilder.Entity("SellerBox.Models.Database.CheckedSubscribersInRepostScenarios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DtCheck");

                    b.Property<Guid?>("IdRepostScenario");

                    b.Property<Guid>("IdSubscriber");

                    b.HasKey("Id");

                    b.HasIndex("IdRepostScenario");

                    b.HasIndex("IdSubscriber");

                    b.ToTable("CheckedSubscribersInRepostScenarios");
                });

            modelBuilder.Entity("SellerBox.Models.Database.Files", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Content");

                    b.Property<DateTime>("DtAdd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name");

                    b.Property<long>("Size");

                    b.Property<string>("VkUrl");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("SellerBox.Models.Database.FilesInMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IdFile");

                    b.Property<Guid>("IdMessage");

                    b.HasKey("Id");

                    b.HasIndex("IdFile");

                    b.HasIndex("IdMessage");

                    b.ToTable("FilesInMessage");
                });

            modelBuilder.Entity("SellerBox.Models.Database.GroupAdmins", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DtConnect")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdGroup");

                    b.Property<string>("IdUser");

                    b.HasKey("Id");

                    b.HasIndex("IdGroup");

                    b.HasIndex("IdUser");

                    b.ToTable("GroupAdmins");
                });

            modelBuilder.Entity("SellerBox.Models.Database.Groups", b =>
                {
                    b.Property<long>("IdVk");

                    b.Property<string>("AccessToken");

                    b.Property<string>("CallbackConfirmationCode");

                    b.Property<string>("Name");

                    b.Property<string>("Photo");

                    b.HasKey("IdVk");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_Birthday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdGroup");

                    b.Property<Guid>("IdSubscriber");

                    b.HasKey("Id");

                    b.HasIndex("IdGroup");

                    b.HasIndex("IdSubscriber");

                    b.ToTable("History_Birthday");
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_BirthdayWall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdGroup");

                    b.Property<Guid>("IdPost");

                    b.Property<long>("IdVkUser");

                    b.HasKey("Id");

                    b.HasIndex("IdGroup");

                    b.HasIndex("IdPost")
                        .IsUnique();

                    b.HasIndex("IdVkUser");

                    b.ToTable("History_BirthdayWall");
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_GroupActions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActionType");

                    b.Property<DateTime>("Dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdGroup");

                    b.Property<Guid>("IdSubscriber");

                    b.HasKey("Id");

                    b.HasIndex("IdGroup");

                    b.HasIndex("IdSubscriber");

                    b.ToTable("History_GroupActions");
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_Messages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Dt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdMessage");

                    b.Property<Guid>("IdSubscriber");

                    b.Property<bool>("IsOutgoingMessage");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("IdMessage");

                    b.HasIndex("IdSubscriber");

                    b.ToTable("History_Messages");
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_Scenarios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Dt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdScenario");

                    b.Property<Guid>("IdSubscriber");

                    b.HasKey("Id");

                    b.HasIndex("IdScenario");

                    b.HasIndex("IdSubscriber");

                    b.ToTable("History_Scenarios");
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_ShortUrlClicks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Dt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdShortUrl");

                    b.Property<Guid?>("IdSubscriber");

                    b.HasKey("Id");

                    b.HasIndex("IdShortUrl");

                    b.HasIndex("IdSubscriber");

                    b.ToTable("History_ShortUrlClicks");
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_SubscribersInChainSteps", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Dt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdChainStep");

                    b.Property<Guid>("IdSubscriber");

                    b.HasKey("Id");

                    b.HasIndex("IdChainStep");

                    b.HasIndex("IdSubscriber");

                    b.ToTable("History_SubscribersInChainSteps");
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_SubscribersInChatScenariosContents", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Dt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdChatScenarioContent");

                    b.Property<Guid>("IdSubscriber");

                    b.HasKey("Id");

                    b.HasIndex("IdChatScenarioContent");

                    b.HasIndex("IdSubscriber");

                    b.ToTable("History_SubscribersInChatScenariosContents");
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_Synchronization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Dt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtEnd")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdGroup");

                    b.Property<byte>("SyncType");

                    b.HasKey("Id");

                    b.HasIndex("IdGroup");

                    b.ToTable("SyncHistory");
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_WallPosts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Dt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdPost");

                    b.Property<Guid>("IdSubscriber");

                    b.Property<bool>("IsRepost");

                    b.HasKey("Id");

                    b.HasIndex("IdPost");

                    b.HasIndex("IdSubscriber");

                    b.ToTable("History_WallPosts");
                });

            modelBuilder.Entity("SellerBox.Models.Database.Logs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Callsite");

                    b.Property<string>("Exception");

                    b.Property<byte>("Level");

                    b.Property<DateTime>("Logged")
                        .HasColumnType("datetime2");

                    b.Property<string>("Logger")
                        .HasMaxLength(50);

                    b.Property<string>("Message");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("SellerBox.Models.Database.Messages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("IdGroup");

                    b.Property<bool>("IsImageFirst");

                    b.Property<string>("Keyboard");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("IdGroup");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SellerBox.Models.Database.Notifications", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DtCreate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ElementType");

                    b.Property<string>("IdElement");

                    b.Property<long>("IdGroup");

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("NotificationType");

                    b.Property<string>("NotifyTo");

                    b.HasKey("Id");

                    b.HasIndex("IdGroup");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SellerBox.Models.Database.RepostScenarios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CheckAfterSeconds");

                    b.Property<bool>("CheckAllPosts");

                    b.Property<bool>("CheckIsSubscriber");

                    b.Property<bool>("CheckLastPosts");

                    b.Property<Guid>("IdCheckingChainContent");

                    b.Property<Guid?>("IdGoToChain");

                    b.Property<Guid?>("IdGoToErrorChain1");

                    b.Property<Guid?>("IdGoToErrorChain2");

                    b.Property<Guid?>("IdGoToErrorChain3");

                    b.Property<Guid?>("IdPost");

                    b.Property<bool>("IsEnabled");

                    b.Property<int?>("LastPostsCount");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("IdCheckingChainContent");

                    b.HasIndex("IdGoToChain");

                    b.HasIndex("IdGoToErrorChain1");

                    b.HasIndex("IdGoToErrorChain2");

                    b.HasIndex("IdGoToErrorChain3");

                    b.HasIndex("IdPost");

                    b.ToTable("RepostScenarios");
                });

            modelBuilder.Entity("SellerBox.Models.Database.Scenarios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("Action");

                    b.Property<Guid?>("IdChain");

                    b.Property<Guid?>("IdChain2");

                    b.Property<Guid?>("IdErrorMessage");

                    b.Property<long>("IdGroup");

                    b.Property<Guid?>("IdMessage");

                    b.Property<string>("InputMessage");

                    b.Property<bool>("IsEnabled");

                    b.Property<bool>("IsStrictMatch");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("IdChain");

                    b.HasIndex("IdChain2");

                    b.HasIndex("IdErrorMessage");

                    b.HasIndex("IdGroup");

                    b.HasIndex("IdMessage");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("SellerBox.Models.Database.Scheduler_Messaging", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DtAdd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtStart")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdMessage");

                    b.Property<string>("Name");

                    b.Property<long>("RecipientsCount");

                    b.Property<byte>("Status");

                    b.Property<string>("VkUserIds");

                    b.HasKey("Id");

                    b.HasIndex("IdMessage");

                    b.ToTable("Scheduler_Messaging");
                });

            modelBuilder.Entity("SellerBox.Models.Database.Segments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DtCreate")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdGroup");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("IdGroup");

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("SellerBox.Models.Database.ShortUrls", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("IdChain");

                    b.Property<long>("IdGroup");

                    b.Property<bool>("IsSingleClick");

                    b.Property<bool>("IsSubscriberRequired");

                    b.Property<string>("Name");

                    b.Property<string>("RedirectTo");

                    b.HasKey("Id");

                    b.HasIndex("IdChain");

                    b.HasIndex("IdGroup");

                    b.ToTable("ShortUrls");
                });

            modelBuilder.Entity("SellerBox.Models.Database.ShortUrlsPassedClicks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Dt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdShortUrlsScenario");

                    b.Property<Guid>("IdSubscriber");

                    b.HasKey("Id");

                    b.HasIndex("IdShortUrlsScenario");

                    b.HasIndex("IdSubscriber");

                    b.ToTable("ShortUrlsPassedClicks");
                });

            modelBuilder.Entity("SellerBox.Models.Database.ShortUrlsScenarios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CheckAfterSeconds");

                    b.Property<bool>("CheckIsSubscriber");

                    b.Property<Guid>("IdCheckingChainContent");

                    b.Property<Guid?>("IdGoToChain");

                    b.Property<Guid?>("IdGoToErrorChain1");

                    b.Property<Guid?>("IdGoToErrorChain2");

                    b.Property<Guid?>("IdGoToErrorChain3");

                    b.Property<Guid?>("IdShortUrl");

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("IdCheckingChainContent");

                    b.HasIndex("IdGoToChain");

                    b.HasIndex("IdGoToErrorChain1");

                    b.HasIndex("IdGoToErrorChain2");

                    b.HasIndex("IdGoToErrorChain3");

                    b.HasIndex("IdShortUrl");

                    b.ToTable("ShortUrlsScenarios");
                });

            modelBuilder.Entity("SellerBox.Models.Database.SubscriberChatReplies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Dt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdChatScenarioContent");

                    b.Property<Guid>("IdSubscriber");

                    b.Property<string>("Text");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("IdChatScenarioContent");

                    b.HasIndex("IdSubscriber");

                    b.ToTable("SubscriberChatReplies");
                });

            modelBuilder.Entity("SellerBox.Models.Database.SubscriberReposts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DtRepost")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdPost");

                    b.Property<Guid>("IdSubscriber");

                    b.Property<bool>("IsProcessed");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("IdPost");

                    b.HasIndex("IdSubscriber");

                    b.ToTable("SubscriberReposts");
                });

            modelBuilder.Entity("SellerBox.Models.Database.Subscribers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DtAdd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtUnsubscribe")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdGroup");

                    b.Property<long>("IdVkUser");

                    b.Property<bool>("IsBlocked");

                    b.Property<bool?>("IsChatAllowed");

                    b.Property<bool?>("IsSubscribedToGroup");

                    b.Property<bool>("IsUnsubscribed");

                    b.HasKey("Id");

                    b.HasIndex("IdGroup");

                    b.HasIndex("IdVkUser");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("SellerBox.Models.Database.SubscribersInChains", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DtAdd")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdChainStep");

                    b.Property<Guid>("IdSubscriber");

                    b.Property<bool>("IsSended");

                    b.HasKey("Id");

                    b.HasIndex("IdChainStep");

                    b.HasIndex("IdSubscriber");

                    b.ToTable("SubscribersInChains");
                });

            modelBuilder.Entity("SellerBox.Models.Database.SubscribersInChatProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DtAdd")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdChatScenarioContent");

                    b.Property<Guid>("IdSubscriber");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("IdChatScenarioContent");

                    b.HasIndex("IdSubscriber");

                    b.ToTable("SubscribersInChatProgress");
                });

            modelBuilder.Entity("SellerBox.Models.Database.SubscribersInSegments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DtAdd")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdSegment");

                    b.Property<Guid>("IdSubscriber");

                    b.HasKey("Id");

                    b.HasIndex("IdSegment");

                    b.HasIndex("IdSubscriber");

                    b.ToTable("SubscribersInSegments");
                });

            modelBuilder.Entity("SellerBox.Models.Database.Users", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<long>("IdCurrentGroup");

                    b.Property<long>("IdVk");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("SellerBox.Models.Database.VkCallbackMessages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdGroup");

                    b.Property<bool>("IsProcessed");

                    b.Property<string>("Object");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("IdGroup");

                    b.ToTable("VkCallbackMessages");
                });

            modelBuilder.Entity("SellerBox.Models.Database.VkUsers", b =>
                {
                    b.Property<long>("IdVk");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Link");

                    b.Property<string>("PhotoOrig400");

                    b.Property<string>("PhotoSquare50");

                    b.Property<string>("SecondName");

                    b.Property<bool?>("Sex");

                    b.HasKey("IdVk");

                    b.ToTable("VkUsers");
                });

            modelBuilder.Entity("SellerBox.Models.Database.WallPosts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DtAdd")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdGroup");

                    b.Property<long>("IdVk");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("IdGroup");

                    b.ToTable("WallPosts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SellerBox.Models.Database.BirthdayScenarios", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Groups", "Group")
                        .WithMany("BirthdayScenarios")
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SellerBox.Models.Database.Messages", "Message")
                        .WithMany()
                        .HasForeignKey("IdMessage")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SellerBox.Models.Database.BirthdayWallScenarios", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Groups", "Group")
                        .WithMany("BirthdayWallScenarios")
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SellerBox.Models.Database.Messages", "Message")
                        .WithMany()
                        .HasForeignKey("IdMessage")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.VkUsers", "VkUser")
                        .WithMany()
                        .HasForeignKey("IdVkUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SellerBox.Models.Database.ChainContents", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Chains", "Chain")
                        .WithMany()
                        .HasForeignKey("IdChain")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Chains", "ExcludeFromChain")
                        .WithMany()
                        .HasForeignKey("IdExcludeFromChain");

                    b.HasOne("SellerBox.Models.Database.Chains", "GoToChain")
                        .WithMany()
                        .HasForeignKey("IdGoToChain");

                    b.HasOne("SellerBox.Models.Database.Messages", "Message")
                        .WithMany()
                        .HasForeignKey("IdMessage");
                });

            modelBuilder.Entity("SellerBox.Models.Database.Chains", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Groups", "Group")
                        .WithMany()
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SellerBox.Models.Database.ChatScenarioContents", b =>
                {
                    b.HasOne("SellerBox.Models.Database.ChatScenarios", "ChatScenario")
                        .WithMany("ChatScenarioContents")
                        .HasForeignKey("IdChatScenario")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SellerBox.Models.Database.ChatScenarios", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Groups", "Group")
                        .WithMany()
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SellerBox.Models.Database.CheckedSubscribersInRepostScenarios", b =>
                {
                    b.HasOne("SellerBox.Models.Database.RepostScenarios", "RepostScenario")
                        .WithMany()
                        .HasForeignKey("IdRepostScenario");

                    b.HasOne("SellerBox.Models.Database.Subscribers", "Subscriber")
                        .WithMany("CheckedSubscribersInRepostScenarios")
                        .HasForeignKey("IdSubscriber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SellerBox.Models.Database.FilesInMessage", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Files", "File")
                        .WithMany()
                        .HasForeignKey("IdFile")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Messages", "Message")
                        .WithMany("Files")
                        .HasForeignKey("IdMessage")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SellerBox.Models.Database.GroupAdmins", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Groups", "Group")
                        .WithMany("GroupAdmins")
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Users", "User")
                        .WithMany()
                        .HasForeignKey("IdUser");
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_Birthday", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Groups", "Group")
                        .WithMany()
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Subscribers", "Subscriber")
                        .WithMany("History_Birthday")
                        .HasForeignKey("IdSubscriber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_BirthdayWall", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Groups", "Group")
                        .WithMany()
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.WallPosts", "WallPost")
                        .WithOne("BirthdayWallHistory")
                        .HasForeignKey("SellerBox.Models.Database.History_BirthdayWall", "IdPost")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SellerBox.Models.Database.VkUsers", "VkUser")
                        .WithMany()
                        .HasForeignKey("IdVkUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_GroupActions", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Groups", "Group")
                        .WithMany()
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Subscribers", "Subscriber")
                        .WithMany("History_GroupActions")
                        .HasForeignKey("IdSubscriber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_Messages", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Messages", "Message")
                        .WithMany()
                        .HasForeignKey("IdMessage");

                    b.HasOne("SellerBox.Models.Database.Subscribers", "Subscriber")
                        .WithMany("History_Messages")
                        .HasForeignKey("IdSubscriber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_Scenarios", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Scenarios", "Scenario")
                        .WithMany()
                        .HasForeignKey("IdScenario")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Subscribers", "Subscriber")
                        .WithMany("History_Scenarios")
                        .HasForeignKey("IdSubscriber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_ShortUrlClicks", b =>
                {
                    b.HasOne("SellerBox.Models.Database.ShortUrls", "ShortUrl")
                        .WithMany()
                        .HasForeignKey("IdShortUrl")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Subscribers", "Subscriber")
                        .WithMany("History_ShortUrlClicks")
                        .HasForeignKey("IdSubscriber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_SubscribersInChainSteps", b =>
                {
                    b.HasOne("SellerBox.Models.Database.ChainContents", "ChainStep")
                        .WithMany()
                        .HasForeignKey("IdChainStep")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Subscribers", "Subscriber")
                        .WithMany("History_SubscribersInChainSteps")
                        .HasForeignKey("IdSubscriber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_SubscribersInChatScenariosContents", b =>
                {
                    b.HasOne("SellerBox.Models.Database.ChatScenarioContents", "ChatScenarioContent")
                        .WithMany()
                        .HasForeignKey("IdChatScenarioContent")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Subscribers", "Subscriber")
                        .WithMany("History_SubscribersInChatScenariosContents")
                        .HasForeignKey("IdSubscriber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_Synchronization", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Groups", "Group")
                        .WithMany()
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SellerBox.Models.Database.History_WallPosts", b =>
                {
                    b.HasOne("SellerBox.Models.Database.WallPosts", "WallPost")
                        .WithMany()
                        .HasForeignKey("IdPost")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Subscribers", "Subscriber")
                        .WithMany("History_WallPosts")
                        .HasForeignKey("IdSubscriber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SellerBox.Models.Database.Messages", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Groups", "Group")
                        .WithMany()
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SellerBox.Models.Database.Notifications", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Groups", "Group")
                        .WithMany()
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SellerBox.Models.Database.RepostScenarios", b =>
                {
                    b.HasOne("SellerBox.Models.Database.ChainContents", "CheckingChainContent")
                        .WithMany()
                        .HasForeignKey("IdCheckingChainContent")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Chains", "GoToChain")
                        .WithMany()
                        .HasForeignKey("IdGoToChain");

                    b.HasOne("SellerBox.Models.Database.Chains", "GoToErrorChain1")
                        .WithMany()
                        .HasForeignKey("IdGoToErrorChain1");

                    b.HasOne("SellerBox.Models.Database.Chains", "GoToErrorChain2")
                        .WithMany()
                        .HasForeignKey("IdGoToErrorChain2");

                    b.HasOne("SellerBox.Models.Database.Chains", "GoToErrorChain3")
                        .WithMany()
                        .HasForeignKey("IdGoToErrorChain3");

                    b.HasOne("SellerBox.Models.Database.WallPosts", "WallPost")
                        .WithMany()
                        .HasForeignKey("IdPost");
                });

            modelBuilder.Entity("SellerBox.Models.Database.Scenarios", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Chains", "Chain")
                        .WithMany()
                        .HasForeignKey("IdChain");

                    b.HasOne("SellerBox.Models.Database.Chains", "Chain2")
                        .WithMany()
                        .HasForeignKey("IdChain2");

                    b.HasOne("SellerBox.Models.Database.Messages", "ErrorMessage")
                        .WithMany()
                        .HasForeignKey("IdErrorMessage");

                    b.HasOne("SellerBox.Models.Database.Groups", "Group")
                        .WithMany()
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Messages", "Message")
                        .WithMany()
                        .HasForeignKey("IdMessage");
                });

            modelBuilder.Entity("SellerBox.Models.Database.Scheduler_Messaging", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Messages", "Message")
                        .WithMany()
                        .HasForeignKey("IdMessage")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SellerBox.Models.Database.Segments", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Groups", "Group")
                        .WithMany()
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SellerBox.Models.Database.ShortUrls", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Chains", "Chain")
                        .WithMany()
                        .HasForeignKey("IdChain");

                    b.HasOne("SellerBox.Models.Database.Groups", "Group")
                        .WithMany()
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SellerBox.Models.Database.ShortUrlsPassedClicks", b =>
                {
                    b.HasOne("SellerBox.Models.Database.ShortUrlsScenarios", "ShortUrlsScenario")
                        .WithMany()
                        .HasForeignKey("IdShortUrlsScenario")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Subscribers", "Subscriber")
                        .WithMany("ShortUrlsPassedClicks")
                        .HasForeignKey("IdSubscriber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SellerBox.Models.Database.ShortUrlsScenarios", b =>
                {
                    b.HasOne("SellerBox.Models.Database.ChainContents", "CheckingChainContent")
                        .WithMany()
                        .HasForeignKey("IdCheckingChainContent")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Chains", "GoToChain")
                        .WithMany()
                        .HasForeignKey("IdGoToChain");

                    b.HasOne("SellerBox.Models.Database.Chains", "GoToErrorChain1")
                        .WithMany()
                        .HasForeignKey("IdGoToErrorChain1");

                    b.HasOne("SellerBox.Models.Database.Chains", "GoToErrorChain2")
                        .WithMany()
                        .HasForeignKey("IdGoToErrorChain2");

                    b.HasOne("SellerBox.Models.Database.Chains", "GoToErrorChain3")
                        .WithMany()
                        .HasForeignKey("IdGoToErrorChain3");

                    b.HasOne("SellerBox.Models.Database.ShortUrls", "ShortUrl")
                        .WithMany()
                        .HasForeignKey("IdShortUrl");
                });

            modelBuilder.Entity("SellerBox.Models.Database.SubscriberChatReplies", b =>
                {
                    b.HasOne("SellerBox.Models.Database.ChatScenarioContents", "ChatScenarioContent")
                        .WithMany()
                        .HasForeignKey("IdChatScenarioContent")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Subscribers", "Subscriber")
                        .WithMany("SubscriberChatReplies")
                        .HasForeignKey("IdSubscriber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SellerBox.Models.Database.SubscriberReposts", b =>
                {
                    b.HasOne("SellerBox.Models.Database.WallPosts", "WallPost")
                        .WithMany()
                        .HasForeignKey("IdPost")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Subscribers", "Subscriber")
                        .WithMany("SubscriberReposts")
                        .HasForeignKey("IdSubscriber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SellerBox.Models.Database.Subscribers", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Groups", "Group")
                        .WithMany("Subscribers")
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.VkUsers", "VkUser")
                        .WithMany()
                        .HasForeignKey("IdVkUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SellerBox.Models.Database.SubscribersInChains", b =>
                {
                    b.HasOne("SellerBox.Models.Database.ChainContents", "ChainStep")
                        .WithMany()
                        .HasForeignKey("IdChainStep")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Subscribers", "Subscriber")
                        .WithMany("SubscribersInChains")
                        .HasForeignKey("IdSubscriber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SellerBox.Models.Database.SubscribersInChatProgress", b =>
                {
                    b.HasOne("SellerBox.Models.Database.ChatScenarioContents", "ChatScenarioContent")
                        .WithMany()
                        .HasForeignKey("IdChatScenarioContent")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Subscribers", "Subscriber")
                        .WithMany("SubscribersInChatProgress")
                        .HasForeignKey("IdSubscriber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SellerBox.Models.Database.SubscribersInSegments", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Segments", "Segment")
                        .WithMany()
                        .HasForeignKey("IdSegment")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SellerBox.Models.Database.Subscribers", "Subscriber")
                        .WithMany("SubscribersInSegments")
                        .HasForeignKey("IdSubscriber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SellerBox.Models.Database.VkCallbackMessages", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Groups", "Group")
                        .WithMany()
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SellerBox.Models.Database.WallPosts", b =>
                {
                    b.HasOne("SellerBox.Models.Database.Groups", "Group")
                        .WithMany()
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
